name: Smoke-Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        dotnet-ver: ['8.0.x', '6.0.x'] # 6.0.x is the latest version available for .Net Mono

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0' # Allow all history to be fetched (required for versioning).

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-ver }}

      - name: Build solution
        run: dotnet build
